language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - head
bundler_args: --without=localdev
gemfile:
  - gemfiles/chef_10_latest.gemfile
  - gemfiles/chef_11_latest.gemfile
matrix:
  allow_failures:
    - rvm: head
