language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
bundler_args: --without=localdev
gemfile:
  - gemfiles/chef_10_latest.gemfile
  - gemfiles/chef_11_latest.gemfile
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  webhooks: https://www.buildheroes.com/api/projects/ecafb9f9b6badadc0d629c2cffaa4cd732ee47af/builds
